---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: vault-subscription
  namespace: vault
  labels:
    app: vault
spec:
  channel: vault/hashicorp-vault-helm
  name: vault
  packageOverrides:
  - packageName: vault
    packageAlias: vault
    packageOverrides:
    - path: spec
      value:
        global:
          openshift: true
        server:
          ha:
            enabled: true
            raft:
              enabled: true
          affinity: ''
          image:
            repository: registry.connect.redhat.com/hashicorp/vault
            tag: 1.9.0-ubi
          updateStrategyType: "RollingUpdate"
        injector:
          authPath: auth/ocp-local
          image:
            repository: registry.connect.redhat.com/hashicorp/vault-k8s
            tag: 0.14.1-ubi
          agentImage:
            repository: registry.connect.redhat.com/hashicorp/vault
            tag: 1.9.0-ubi
  packageFilter:
    version: "0.18.0"
  placement:
    placementRef:
      kind: PlacementRule
      name: vault
