---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: <PATCH_ME>
  namespace: vault-client
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      app: <PATCH_ME>
