---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: <PATCH_ME>
  namespace: vault-client
  labels:
    app: <PATCH_ME>
spec:
  channel: vault-client/hashicorp-vault-helm
  name: vault
  packageOverrides:
  - packageName: vault
    packageAlias: vault
    packageOverrides:
    - path: spec
      value:
        global:
          openshift: true
        server:
          enabled: false
        injector:
          authPath: <PATCH_ME>
          externalVaultAddr: <PATCH_ME>
          image:
            repository: registry.connect.redhat.com/hashicorp/vault-k8s
            tag: 0.14.1-ubi
          agentImage:
            repository: registry.connect.redhat.com/hashicorp/vault
            tag: 1.9.0-ubi
  packageFilter:
    version: "0.18.0"
  placement:
    placementRef:
      kind: PlacementRule
      name: <PATCH_ME>
