---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acm-configuration
  namespace: acm-configuration
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  pathname: https://gitea.apps.cluster-ch69t.sandbox1624.opentlc.com/lab-user/ilt-rhacm-configuration
  type: Git
  secretRef:
    name: ilt-gitea
