---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ac-cluster-configuration
  namespace: acm-cluster-configuration
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: root
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: acm-cluster-configuration
spec:
  channel: acm-cluster-configuration/acm-cluster-configuration
  placement:
    placementRef:
      kind: PlacementRule
      name: acm-cluster-configuration
