apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-etcd-encryption
  namespace: acm-policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
