---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
    policy.open-cluster-management.io/standards: NIST-CSF
  name: etcd-encryption
  namespace: acm-policy
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: encrypt-etcd
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: APIServer
            metadata:
              name: cluster
            spec:
              encryption:
                type: aescbc
        remediationAction: enforce
        severity: med
  remediationAction: enforce
