---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: aws-secret-access-key
  namespace: acm-secrets
spec:
  clusterSelector:
    matchExpressions:
    - key: vendor
      operator: In
      values:
      - OpenShift
    - key: purpose
      operator: In
      values:
      - development
      - production
