---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: vault-unsealer
  namespace: acm-subscriptions
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchlabels:
      app: vault-unsealer
