---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: vault-unsealer
  namespace: acm-subscriptions
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: cluster-specific/vault-unsealer
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: vault-unsealer
spec:
  channel: acm-configuration/acm-applications
  placement:
    placementRef:
      kind: PlacementRule
      name: vault-unsealer
