apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  namespace: acm-cluster-configuration
  name: cluster-configuration
  annotations:
    apps.open-cluster-management.io/deployables: ''
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - cluster-configuration