---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: vault-client-configuration-ch69t-prod
  namespace: vault-client
spec:
  clusterSelector:
    matchLabels:
      name: ch69t-prod
