---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: vault-client-configuration-ch69t-prod
  namespace: vault-client
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: cluster-specific/vault-client-configuration/overlays/ch69t-prod
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: vault-client-configuration-ch69t-prod
spec:
  channel: acm-configuration/acm-applications
  placement:
    placementRef:
      kind: PlacementRule
      name: vault-client-configuration-ch69t-prod
