---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-openshift-development
  namespace: acm-policy
spec:
  clusterConditions:
  - status: 'True'
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: vendor
      operator: In
      values:
      - OpenShift
    - key: purpose
      operator: In
      values:
      - development
