---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cert-manager-config-ch69t-dev
  namespace: acm-subscriptions
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: cert-manager-config-ch69t-dev
