---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: agents-ch69t-prod
  namespace: acm-subscriptions
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      app: agents-ch69t-prod
