---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: vault-unseal-keys
  namespace: acm-secrets
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'
