---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: vault-token
  namespace: acm-secrets
spec:
  clusterSelector:
    matchExpressions:
    - key: purpose
      operator: In
      values:
      - development
      - production
