---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: self-provisioner-absent
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: self-provisioner-absent
      spec:
        object-templates:
        - complianceType: mustnothave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: self-provisioners
        remediationAction: enforce
        severity: med
  remediationAction: enforce
